export const LOOK_PRESETS = Object.freeze({
  studio: Object.freeze({
    top: '#20242a',
    bottom: '#060708',
    accent: '#ff7950',
    accentStrength: 0.13,
    floor: '#111316',
    floorRoughness: 0.7,
    exposure: 1.05,
    environment: 1.25,
    key: 3.4,
    fill: 1.05,
    rim: 5.0,
    keyColor: '#fff7ee',
    fillColor: '#b7c8dd',
    rimColor: '#ff7950',
    bloom: 0.18,
    shadow: 0.48,
  }),
  soft: Object.freeze({
    top: '#e9e8e3',
    bottom: '#999b9c',
    accent: '#ffffff',
    accentStrength: 0.1,
    floor: '#c6c6c2',
    floorRoughness: 0.82,
    exposure: 0.94,
    environment: 1.15,
    key: 2.45,
    fill: 1.7,
    rim: 1.65,
    keyColor: '#fffaf3',
    fillColor: '#dce7f0',
    rimColor: '#ffffff',
    bloom: 0.05,
    shadow: 0.27,
  }),
  noir: Object.freeze({
    top: '#0b0b0c',
    bottom: '#010101',
    accent: '#e54820',
    accentStrength: 0.08,
    floor: '#050506',
    floorRoughness: 0.48,
    exposure: 0.92,
    environment: 0.52,
    key: 1.25,
    fill: 0.12,
    rim: 7.2,
    keyColor: '#d8e2ef',
    fillColor: '#5f7188',
    rimColor: '#ff5c31',
    bloom: 0.36,
    shadow: 0.62,
  }),
  gallery: Object.freeze({
    top: '#29364e',
    bottom: '#080b12',
    accent: '#7aa2ff',
    accentStrength: 0.12,
    floor: '#151a24',
    floorRoughness: 0.58,
    exposure: 1.08,
    environment: 1.6,
    key: 2.85,
    fill: 1.15,
    rim: 2.9,
    keyColor: '#eef4ff',
    fillColor: '#7da6ff',
    rimColor: '#b5caff',
    bloom: 0.13,
    shadow: 0.42,
  }),
  sunset: Object.freeze({
    top: '#5a2720',
    bottom: '#120708',
    accent: '#ff9b6b',
    accentStrength: 0.21,
    floor: '#1c0d0b',
    floorRoughness: 0.63,
    exposure: 0.98,
    environment: 0.72,
    key: 3.7,
    fill: 0.58,
    rim: 5.6,
    keyColor: '#ffd2a2',
    fillColor: '#7d4952',
    rimColor: '#ff7950',
    bloom: 0.25,
    shadow: 0.51,
  }),
});

export const CAMERA_PRESETS = Object.freeze({
  hero: Object.freeze({ direction: [1.1, 0.48, 1.65], distance: 1.02, targetY: 0.47 }),
  front: Object.freeze({ direction: [0, 0.18, 1], distance: 1.02, targetY: 0.48 }),
  side: Object.freeze({ direction: [1, 0.2, 0], distance: 1.05, targetY: 0.48 }),
  top: Object.freeze({ direction: [0.32, 1, 0.34], distance: 1.08, targetY: 0.42 }),
  detail: Object.freeze({ direction: [0.9, 0.34, 1.25], distance: 0.58, targetY: 0.65 }),
});

export const QUALITY_PROFILES = Object.freeze({
  performance: Object.freeze({ maxPixelRatio: 1, shadowMapSize: 1024 }),
  balanced: Object.freeze({ maxPixelRatio: 1.45, shadowMapSize: 1536 }),
  quality: Object.freeze({ maxPixelRatio: 2, shadowMapSize: 2048 }),
});

export const DEFAULT_PROJECT_STATE = Object.freeze({
  schemaVersion: 1,
  model: Object.freeze({
    name: 'Demo Object',
    fileSize: null,
    procedural: true,
    materialMode: 'original',
    userScale: 1,
    userOffset: 0,
  }),
  studio: Object.freeze({
    preset: 'studio',
    exposure: LOOK_PRESETS.studio.exposure,
    environment: LOOK_PRESETS.studio.environment,
    key: LOOK_PRESETS.studio.key,
    rim: LOOK_PRESETS.studio.rim,
    bloom: LOOK_PRESETS.studio.bloom,
    floorEnabled: true,
    shadowsEnabled: true,
    postEnabled: true,
  }),
  camera: Object.freeze({
    preset: 'hero',
    focalLength: 50,
    damping: 0.08,
    autoRotate: false,
    horizonLocked: true,
  }),
  motion: Object.freeze({
    clipIndex: 0,
    playing: false,
    loop: true,
    speed: 1,
    turntable: false,
    turntableSpeed: 0.3,
  }),
  render: Object.freeze({
    quality: 'quality',
  }),
});
